version: '3'
services:

    web:
        build:
            dockerfile: Dockerfile.local
            context: ./
        # During development we map local files into the container
        volumes:
            # Map current working copy into the container
            - ./:/var/www/html/

            # Uncomment to use dev specific PHP settings
            - ./config/php/local.ini:/etc/php7/conf.d/99-local.ini

            # Uncomment to use the local vendor directory, e.g. for debugging.
            # This requires that you have copied the directory to your host with
            #   docker-compose run --rm web cp -ra /var/www/vendor .
            #- ./vendor:/var/www/vendor
        links:
            - db
        environment:
            # Make sure to tweak this in production
            PHP_FPM_MAX_CHILDREN: 5
            YII_DEBUG: 1
            YII_ENV: dev
            COOKIE_VALIDATION_KEY: local
            DB_DSN: mysql:host=db;dbname=exbico
            DB_USER: exbico
            DB_PASSWORD: password
            PHP_IDE_CONFIG: serverName=exbico
        ports:
            - "8080:80"

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: exbico
            MYSQL_USER: exbico
            MYSQL_PASSWORD: password
